# Generated by Django 5.0.1 on 2025-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_file"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
