# Generated by Django 5.0.1 on 2025-06-26 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileversion",
            options={"ordering": ["-version_number"]},
        ),
        migrations.AddField(
            model_name="file",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="file",
            name="url_path",
            field=models.CharField(max_length=1024, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="file",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="file_versions.file",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="storage_path",
            field=models.FileField(default=None, upload_to="versions/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="uploaded_by",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="version_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("file", "version_number")},
        ),
    ]
