# Generated by Django 5.0.1 on 2025-06-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0004_alter_fileversion_options_file_is_latest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBlob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("data", models.BinaryField()),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CAS Content Blob",
            },
        ),
        migrations.RemoveField(
            model_name="fileversion",
            name="storage_path",
        ),
        migrations.AddField(
            model_name="fileversion",
            name="content_blob",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to="file_versions.contentblob"
            ),
            preserve_default=False,
        ),
    ]
