# Generated by Django 5.0.1 on 2025-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_contentblob_remove_fileversion_storage_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="url_path",
            field=models.CharField(default=None, max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
