# Generated by Django 5.0.1 on 2025-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_alter_file_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="url_path",
            field=models.CharField(max_length=1024),
        ),
    ]
