# Generated by Django 5.0.1 on 2025-06-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0007_alter_file_url_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="is_latest",
        ),
        migrations.AddField(
            model_name="fileversion",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
    ]
