# Generated by Django 5.0.1 on 2025-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0008_remove_file_is_latest_fileversion_is_latest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblob",
            name="content_hash",
            field=models.CharField(max_length=64),
        ),
    ]
