from django.urls import reverse
from propylon_document_manager.file_versions.models import User
from rest_framework import status
from rest_framework.test import APIClient
from .factories import UserFactory


client = APIClient()

def test_login_success():
    password = 'testpass123'
    user = UserFactory(password=password)  # email and name will be random
    
    url = reverse('api:login-list')
    response = client.post(url, {
        'email': user.email,  # Use the email generated by the factory
        'password': password
    }, format='json')
    
    assert response.status_code == status.HTTP_200_OK
    assert 'token' in response.data
    assert 'user' in response.data
    assert response.data['user']['email'] == user.email
    assert 'password' not in response.data['user']


def test_login_failure_wrong_password():
    # Create test user
    password = 'correctpass'
    user = UserFactory(password=password)  # email and name will be random
    
    url = reverse('api:login-list')
    response = client.post(url, {
        'email': 'test@example.com',
        'password': 'wrongpass'
    }, format='json')
    
    assert response.status_code == status.HTTP_400_BAD_REQUEST
    assert 'error' in response.data
    assert response.data['error'] == 'Invalid Credentials'
